Repository JNU-econovation/BuddyBridge_FE, pull requests merged in 2024-09, with the labels that each got.

#69 feat: 댓글 작성자 추가 정보 보여주기
  src/components/common/Comment/Comment.module.scss
  src/components/common/Comment/Comment.tsx
  src/components/common/Post/Post.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.tsx
  src/components/page-layout/myPageLayout/components/MyInfo/MyInfo.tsx
Labels: feat, refactor

#71 feat: 마이페이지 게시글 댓글 목록추가
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/Footer.tsx
  src/components/common/MyPageMyInfo/MyPageMyInfo.module.scss
  src/components/common/MyPageMyInfo/MyPageMyInfo.tsx
  src/components/common/MyWriteComment/MyWriteComment.module.scss
  src/components/common/MyWriteComment/MyWriteComment.tsx
  src/components/common/MyWriteListBox/MyWriteList/MyWriteList.module.scss
  src/components/common/MyWriteListBox/MyWriteList/MyWriteList.tsx
  src/components/common/MyWriteListBox/MyWriteListBox.module.scss
  src/components/common/MyWriteListBox/MyWriteListBox.tsx
  src/components/common/MyWriteListBox/PaginationBox/PaginationBox.module.scss
  src/components/common/MyWriteListBox/PaginationBox/PaginationBox.tsx
  src/components/common/MyWriteListBox/SelectFilter/SelectFilter.module.scss
  src/components/common/MyWriteListBox/SelectFilter/SelectFilter.tsx
  src/components/common/MyWritePost/MyWritePost.module.scss
  src/components/common/MyWritePost/MyWritePost.tsx
  src/components/common/Pagenation/Pagenation.module.scss
  src/components/common/RootLayout/RootLayout.tsx
  src/components/page-layout/MyPageHelpYouLayout/MyPageHelpYouLayout.module.scss
  src/components/page-layout/MyPageHelpYouLayout/MyPageHelpYouLayout.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.module.scss
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.tsx
  src/components/page-layout/myPageHelpMeLayout/apis/getMyComment.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyPost.ts
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.module.scss
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.tsx
  src/components/page-layout/myPageHelpMeLayout/components/myPageHelpMeLayout.module.scss
  src/components/page-layout/myPageHelpMeLayout/components/myPageHelpMeLayout.tsx
  src/components/page-layout/myPageLayout/components/MyInfo/MyInfo.module.scss
  src/components/page-layout/myPageLayout/components/MyPageNav/MyPageNav.tsx
  src/hooks/useGetMyComment.ts
  src/hooks/useGetMyPost.ts
  src/pages/index.tsx
  src/pages/my-page/edit/index.tsx
  src/pages/my-page/help-me/index.tsx
  src/pages/my-page/help-you/index.tsx
  src/pages/my-page/index.tsx
  src/types/user/index.ts
  src/utils/index.ts
Labels: feat

#78 refactor: target 브랜치 변경
  .github/workflows/deploy.yml
Labels: refactor

#81 hotfix: 잘못된 import 구문 수정
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/Header/User/User.tsx
  src/components/common/Header/apis/getLogOut.ts
  src/components/common/Header/apis/postLogOut.ts
  src/components/page-layout/HomeLayout/components/HomeLayout.tsx
  src/pages/my-page/help-you/index.tsx
Labels: bug, refactor

#83 feat: 댓글 수정 기능 추가
  src/components/common/Comment/Comment.module.scss
  src/components/common/Comment/Comment.tsx
  src/components/common/Comment/apis/putComment.ts
Labels: feat

#85 refactor: 마이페이지에서 내 정보를 관리하던 zustand를 tanstack query로 변경
  src/components/page-layout/myPageLayout/components/MyInfo/MyInfo.tsx
Labels: refactor

#88 refactor: 댓글 수정할 때 나오는 textarea 너비수정
  src/components/common/Comment/Comment.module.scss
  src/components/common/Comment/Comment.tsx
  src/components/common/Post/Post.module.scss
  src/components/common/Post/Post.tsx
  src/components/page-layout/loginLayout/components/loginLayout.tsx
Labels: refactor

#89 refactor: 사용안하는 import 구문 삭제
  src/components/common/Post/Post.tsx
Labels: refactor
