Repository JNU-econovation/BuddyBridge_FE, pull requests merged in 2024-10, with the labels that each got.

#92 feat: 찜하기 관련 기능 추가
  public/icons/heart.svg
  public/icons/red_haert.svg
  public/icons/red_heart.svg
  src/components/common/LikesPost/LikesPost.module.scss
  src/components/common/LikesPost/LikesPost.tsx
  src/components/common/Pagenation/apis/getHelpMeList.ts
  src/components/common/Post/Post.tsx
  src/components/common/Post/apis/postLikes.ts
  src/components/common/PostStatusLabel/PostStatusLabel.module.scss
  src/components/common/PostStatusLabel/PostStatusLabel.tsx
  src/components/page-layout/HomeLayout/apis/getGiverPost.ts
  src/components/page-layout/HomeLayout/apis/getTakerPost.ts
  src/components/page-layout/HomeLayout/types/index.ts
  src/components/page-layout/myPageLayout/constants/index.ts
  src/components/page-layout/myPageLikesLayout/apis/getMyLikes.ts
  src/components/page-layout/myPageLikesLayout/components/MyLikesList/MyLikesList.module.scss
  src/components/page-layout/myPageLikesLayout/components/MyLikesList/MyLikesList.tsx
  src/components/page-layout/myPageLikesLayout/components/MyLikesListBox/MyLikesListBox.module.scss
  src/components/page-layout/myPageLikesLayout/components/MyLikesListBox/MyLikesListBox.tsx
  src/components/page-layout/myPageLikesLayout/components/MyPageLikesList/MyPageLikesList.module.scss
  src/components/page-layout/myPageLikesLayout/components/MyPageLikesList/MyPageLikesList.tsx
  src/components/page-layout/myPageLikesLayout/components/PostTypeFilter/PostTypeFilter.module.scss
  src/components/page-layout/myPageLikesLayout/components/PostTypeFilter/PostTypeFilter.tsx
  src/components/page-layout/myPageLikesLayout/components/myPageLikesLayout.module.scss
  src/components/page-layout/myPageLikesLayout/components/myPageLikesLayout.tsx
  src/constants/route.ts
  src/pages/my-page/likes/index.tsx
  src/styles/globals.scss
  src/styles/reset.scss
Labels: feat

#95 feat: 알람 읽기 기능 추가, SSE 알람과 이전에 온 알람 합치기
  src/components/common/Header/User/Login/AlarmDropDown/AlarmDropDown.module.scss
  src/components/common/Header/User/Login/AlarmDropDown/AlarmDropDown.tsx
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/apis/getNotifications.ts
  src/components/common/Header/apis/postReadAllNotification.ts
  src/components/common/Header/apis/postReadNotification.ts
  src/components/common/Header/hooks/useNotification.ts
  src/components/common/Header/hooks/useReadNotification.ts
  src/components/common/Header/utils/index.ts
Labels: refactor

#100 refactor: 헤더 수정
  public/images/logo.svg
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/constants/route.ts
Labels: refactor

#102 feat: 구글 애널리틱스 적용
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: feat

#104 fix: 타입 에러 수정
  src/components/common/Header/User/Login/Login.tsx
Labels: bug

#97 refactor: 로그인 페이지 UI 수정
  public/images/loginImg.svg
  src/components/page-layout/loginLayout/components/loginLayout.module.scss
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/styles/_mixin.scss
Labels: refactor

#106 fix: zIndex 파일 제거
  src/components/common/DropDown/DropDown.module.scss
  src/components/common/Header/User/DropDown/DropDown.module.scss
  src/styles/_zindex.scss
  src/styles/globals.scss
Labels: bug

#108 refactor: 구글 애널리틱스 수정
  src/lib/GoogleAnalytics.tsx
  src/pages/_app.tsx
Labels: refactor

#109 refactor: post 컴포넌트 UI 수정
  public/icons/calendar.svg
  public/icons/clock.svg
  public/icons/location.svg
  public/icons/personnel.svg
  src/assets/fonts/NanumSquareNeo-Variable.ttf
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/LikesPost/LikesPost.tsx
  src/components/common/MyWriteComment/MyWriteComment.tsx
  src/components/common/MyWritePost/MyWritePost.tsx
  src/components/common/Post/Post.module.scss
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostLabel/PostLabel.module.scss
  src/components/common/Post/PostLabel/PostLabel.tsx
  src/components/page-layout/HomeLayout/types/index.ts
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/myPageLikesLayout/apis/getMyLikes.ts
  src/components/page-layout/myPageLikesLayout/components/MyLikesList/MyLikesList.tsx
  src/styles/_colors.scss
  src/styles/_fonts.scss
  src/utils/index.ts
Labels: refactor

#93 feat: 게시글 필터링 기능 추가
  package-lock.json
  package.json
  src/components/common/Filter/Filter.module.scss
  src/components/common/Filter/Filter.tsx
  src/components/common/Filter/constants/index.ts
  src/components/common/Pagenation/apis/getHelpMeList.ts
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
Labels: feat
