Repository JNU-econovation/BuddyBridge_FE, pull requests merged in 2024-11, with the labels that each got.

#111 feat: 댓글 하나만 작성 가능하도록 기능 추가
  src/components/common/commentWrite/commentWrite.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
Labels: feat

#115 refactor: 게시물 작성 페이지, 게시물 상세 페이지 수정
  src/components/common/DropDown/constants/index.ts
  src/components/common/Post/Post.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.module.scss
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/types/index.ts
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.module.scss
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
  src/utils/index.ts
Labels: refactor

#113 refactor: 작성하기 버튼 및 타이틀 글자 스타일 변경
  public/icons/send_arrow.svg
  src/components/common/Filter/Filter.module.scss
  src/components/common/Filter/Filter.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
Labels: refactor

#117 bug: 작성하기 버튼 url 변경
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
Labels: bug, refactor

#120 refactor: 로그인 페이지 수정
  README.md
  package-lock.json
  package.json
  public/icons/email.svg
  public/icons/kakao.svg
  public/icons/name.svg
  public/icons/password.svg
  src/apis/axiosInstance.ts
  src/apis/getNewAccessToken.ts
  src/components/common/Comment/apis/deleteComment.ts
  src/components/common/Comment/apis/postChatAccept.ts
  src/components/common/Comment/apis/putComment.ts
  src/components/common/DatePicker/DatePicker.module.scss
  src/components/common/DatePicker/DatePicker.tsx
  src/components/common/DropDown/DropDown.module.scss
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/constants/index.ts
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/Header/User/User.tsx
  src/components/common/Header/apis/getLogIn.ts
  src/components/common/Header/apis/getNotifications.ts
  src/components/common/Header/apis/postLogOut.ts
  src/components/common/Header/apis/postReadAllNotification.ts
  src/components/common/Header/apis/postReadNotification.ts
  src/components/common/Modal/Modal.module.scss
  src/components/common/Modal/Modal.tsx
  src/components/common/ModalPortal/ModalPortal.tsx
  src/components/common/Pagenation/apis/getHelpMeList.ts
  src/components/common/Post/apis/postLikes.ts
  src/components/common/SignLayout/SignLayout.module.scss
  src/components/common/SignLayout/SignLayout.tsx
  src/components/common/commentWrite/apis/postComment.ts
  src/components/page-layout/HomeLayout/apis/getGiverPost.ts
  src/components/page-layout/HomeLayout/apis/getKakaoInfo.ts
  src/components/page-layout/HomeLayout/apis/getTakerPost.ts
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.tsx
  src/components/page-layout/chatLayout/apis/getAllChatList.ts
  src/components/page-layout/chatLayout/apis/getChatingRoom.ts
  src/components/page-layout/chatLayout/apis/putMatchingStatus.ts
  src/components/page-layout/helpMeDetailLayout/apis/deletePost.ts
  src/components/page-layout/helpMeDetailLayout/apis/getTakerDetail.ts
  src/components/page-layout/helpMeRegisterLayout/apis/postHelpMeRegister.ts
  src/components/page-layout/helpYouDetailLayout/apis/getAllComment.ts
  src/components/page-layout/helpYouDetailLayout/apis/getGiverDetail.ts
  src/components/page-layout/loginLayout/apis/getTestLogin.ts
  src/components/page-layout/loginLayout/apis/postLogin.ts
  src/components/page-layout/loginLayout/components/loginLayout.module.scss
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/components/page-layout/myPageEditLayout/apis/getMyInfo.ts
  src/components/page-layout/myPageEditLayout/apis/putMyInfo.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyComment.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyPost.ts
  src/components/page-layout/myPageLikesLayout/apis/getMyLikes.ts
  src/components/page-layout/signUpLayout/apis/postSignUp.ts
  src/components/page-layout/signUpLayout/components/signUpLayout.module.scss
  src/components/page-layout/signUpLayout/components/signUpLayout.tsx
  src/constants/route.ts
  src/pages/login/index.tsx
  src/pages/sign-up/index.tsx
  src/styles/_fonts.scss
Labels: feat, refactor

#123 refactor: 게시글 작성 페이지 수정
  package-lock.json
  package.json
  src/components/common/Comment/Comment.tsx
  src/components/common/DropDown/DropDown.module.scss
  src/components/common/Filter/Filter.tsx
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/User/User.tsx
  src/components/common/Header/apis/postLogOut.ts
  src/components/common/MyInfoCard/MyInfoCard.module.scss
  src/components/common/MyInfoCard/MyInfoCard.tsx
  src/components/common/MyPageMyInfo/MyPageMyInfo.tsx
  src/components/common/Pagenation/apis/getHelpMeList.ts
  src/components/common/Post/Post.tsx
  src/components/common/RadioInput/RadioInput.module.scss
  src/components/common/RadioInput/RadioInput.tsx
  src/components/page-layout/HomeLayout/apis/getGiverPost.ts
  src/components/page-layout/HomeLayout/apis/getKakaoInfo.ts
  src/components/page-layout/HomeLayout/apis/getTakerPost.ts
  src/components/page-layout/HomeLayout/components/HomeLayout.tsx
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.tsx
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ChatingRoomContent.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/apis/postHelpMeRegister.ts
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.module.scss
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/types/index.ts
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.module.scss
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.tsx
  src/stores/kakaoInnfo.ts
Labels: refactor
