Repository JNU-econovation/BuddyBridge_FE, pull requests merged in 2025-01, with the labels that each got.

#133 refactor: 메인페이지 UI 변경(알림 ui 변경)
  package-lock.json
  package.json
  src/components/common/Header/Header.module.scss
  src/components/common/Header/User/Login/AlarmDropDown/AlarmDropDown.module.scss
  src/components/common/Header/User/Login/AlarmDropDown/AlarmDropDown.tsx
  src/components/common/Header/User/Login/AlarmDropDown/AlarmFilter.module.scss
  src/components/common/Header/User/Login/AlarmDropDown/AlarmFilter.tsx
  src/components/common/Header/User/Login/AlarmDropDown/constants/index.ts
  src/components/common/Header/User/Login/Login.module.scss
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/apis/getNotifications.ts
  src/components/common/Header/hooks/useNotification.ts
  src/components/common/Post/Post.module.scss
  src/components/common/RootLayout/RootLayout.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
  src/styles/_colors.scss
Labels: feat, refactor

#139 refactor: 채팅 페이지 수정
  public/icons/alert.svg
  public/icons/chat_arrow.svg
  public/icons/declaration.svg
  src/components/common/Chat/Chat.module.scss
  src/components/common/Chat/Chat.tsx
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/constants/index.ts
  src/components/page-layout/chatLayout/apis/putMatchingStatus.ts
  src/components/page-layout/chatLayout/components/ChatList/ChatList.module.scss
  src/components/page-layout/chatLayout/components/ChatList/ChatList.tsx
  src/components/page-layout/chatLayout/components/ChatList/ChatListContent/ChatListContent.module.scss
  src/components/page-layout/chatLayout/components/ChatList/ChatListContent/ChatListContent.tsx
  src/components/page-layout/chatLayout/components/ChatList/ChatListHeader/ChatListHeader.module.scss
  src/components/page-layout/chatLayout/components/ChatList/MyInfo/MyInfo.module.scss
  src/components/page-layout/chatLayout/components/ChatList/MyInfo/MyInfo.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoom.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoom.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/CertifyVolunteeringModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/CertifyVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/apis/getPostEnums.ts
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/apis/postCertificationsForm.ts
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ChatingRoomContent.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ChatingRoomContent.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CompleteVolunteeringModal/CompleteVolunteeringModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CompleteVolunteeringModal/CompleteVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ConfirmVolunteeringModal/ConfirmVolunteeringModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ConfirmVolunteeringModal/ConfirmVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/DeclarationModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/DeclarationModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/apis/getDeclarationType.ts
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/apis/postMatchingsDeclaration.ts
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/GetNoVolunteeringModal/GetNoVolunteeringModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/GetNoVolunteeringModal/GetNoVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/MyChat/MyChat.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/MyChat/MyChat.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/OppositeChat/OppositeChat.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/OppositeChat/OppositeChat.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomHeader/ChatingRoomHeader.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomHeader/ChatingRoomHeader.tsx
  src/components/page-layout/chatLayout/components/chatLayout.module.scss
  src/components/page-layout/chatLayout/components/chatLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
  src/utils/index.ts
Labels: refactor

#143 refactor: 페이지네이션 관련 코드 수정
  src/components/common/AssistanceTypeFilter/AssistanceTypeFilter.tsx
  src/components/common/LikesPost/LikesPost.tsx
  src/components/common/MyWriteListBox/MyWriteListBox.tsx
  src/components/common/MyWriteListBox/PaginationBox/PaginationBox.tsx
  src/components/common/MyWritePost/MyWritePost.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
  src/components/page-layout/myPageFinishedLayout/apis/getMyFinished.ts
  src/components/page-layout/myPageFinishedLayout/components/FinishedPost/FinishedPost.tsx
  src/components/page-layout/myPageFinishedLayout/components/MyFinishedListBox/MyFinishedListBox.tsx
  src/components/page-layout/myPageHelpMeLayout/apis/getMyComment.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyPost.ts
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.tsx
  src/components/page-layout/myPageLikesLayout/apis/getMyLikes.ts
  src/components/page-layout/myPageLikesLayout/components/MyLikesListBox/MyLikesListBox.tsx
  src/components/page-layout/myPageMyContentLayout/components/MyRegisterPost/myRegisterPost.tsx
  src/hooks/useGetMyComment.ts
  src/hooks/useGetMyPost.ts
  src/pages/my-page/finished/index.tsx
Labels: refactor

#146 refactor: 채팅방 상태 변경
  public/images/bannerImg.svg
  public/images/logo.svg
  src/components/common/Chat/Chat.tsx
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Pagenation/Pagenation.module.scss
  src/components/page-layout/HomeLayout/apis/getGiverPost.ts
  src/components/page-layout/HomeLayout/apis/getTakerPost.ts
  src/components/page-layout/HomeLayout/components/Banner/Banner.module.scss
  src/components/page-layout/HomeLayout/components/Banner/Banner.tsx
  src/components/page-layout/chatLayout/apis/deleteMatching.ts
  src/components/page-layout/chatLayout/apis/postCertificationRequest.ts
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoom.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/CertifyVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ChatingRoomContent.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/ConfirmVolunteeringModal/ConfirmVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomHeader/ChatingRoomHeader.tsx
  src/components/page-layout/chatLayout/components/chatLayout.tsx
Labels: refactor

#147 feat: 옵티미스틱 업데이트 적용
  src/components/common/Header/User/Login/Login.module.scss
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/hooks/useNotification.ts
  src/components/common/Header/utils/index.ts
  src/components/common/Post/Post.tsx
Labels: refactor

#157 refactor: 내 프로필 드롭다운 컴포넌트에 닉네임 렌더링
  public/icons/pink_heart.svg
  public/images/bannerImg.svg
  src/apis/post/index.ts
  src/components/common/Filter/Filter.module.scss
  src/components/common/Footer/Footer.module.scss
  src/components/common/Header/Header.module.scss
  src/components/common/Header/User/DropDown/DropDown.module.scss
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/Header/User/Login/Login.module.scss
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/User/NotLogin/NotLogin.module.scss
  src/components/common/LikesPost/LikesPost.tsx
  src/components/common/MyPageMyInfo/MyPageMyInfo.module.scss
  src/components/common/Pagenation/apis/getHelpMeList.ts
  src/components/common/Post/Post.module.scss
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostLabel/PostLabel.module.scss
  src/components/page-layout/HomeLayout/apis/getGiverPost.ts
  src/components/page-layout/HomeLayout/apis/getTakerPost.ts
  src/components/page-layout/HomeLayout/components/Banner/Banner.module.scss
  src/components/page-layout/HomeLayout/components/Banner/Banner.tsx
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.tsx
  src/components/page-layout/HomeLayout/components/PostList/PostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.module.scss
  src/styles/_fonts.scss
  src/types/error/index.ts
Labels: feat, refactor

#156 feat: 댓글 다중 삭제 구현
  src/components/common/MyWriteFilter/ MyWriteFilter.tsx
  src/components/common/MyWriteFilter/constants/index.ts
  src/components/common/MyWriteListBox/MyWriteList/MyWriteList.tsx
  src/components/common/commentWrite/commentWrite.tsx
  src/components/page-layout/myPageHelpMeLayout/apis/getMyComment.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyPost.ts
  src/components/page-layout/myPageMyContentLayout/apis/deleteComments.ts
  src/components/page-layout/myPageMyContentLayout/components/MyRegisterPost/myRegisterPost.tsx
Labels: feat

#159 refactor: 전체적인 스타일 수정
  src/components/common/Comment/ChatButton/ChatButton.module.scss
  src/components/common/Comment/Comment.module.scss
  src/components/common/LikesPost/LikesPost.tsx
  src/components/common/ReportForm/ReportForm.module.scss
  src/components/common/commentWrite/commentWrite.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.module.scss
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.tsx
  src/components/page-layout/myPageEditLayout/components/myPageEditLayout.module.scss
  src/components/page-layout/myPageFinishedLayout/components/FinishedPost/FinishedPost.tsx
  src/components/page-layout/myPageFinishedLayout/components/MyFinishedListBox/MyFinishedListBox.module.scss
  src/components/page-layout/myPageFinishedLayout/components/MyPageCertifyVolunteeringModal/MyPageCertifyVolunteeringModal.tsx
  src/components/page-layout/myPageFinishedLayout/components/myPageFinishedLayout.module.scss
  src/components/page-layout/myPageLayout/components/MyInfo/MyInfo.module.scss
  src/components/page-layout/myPageLayout/components/MyPageNav/MyPageNav.module.scss
  src/components/page-layout/myPageLayout/components/myPageLayout.module.scss
  src/components/page-layout/myPageLikesLayout/components/MyLikesList/MyLikesList.tsx
  src/components/page-layout/myPageLikesLayout/components/MyLikesListBox/MyLikesListBox.module.scss
  src/components/page-layout/myPageLikesLayout/components/MyLikesListBox/MyLikesListBox.tsx
  src/components/page-layout/myPageLikesLayout/components/myPageLikesLayout.module.scss
  src/components/page-layout/myPageMyContentLayout/components/MyRegisterPost/myRegisterPost.module.scss
  src/components/page-layout/myPageMyContentLayout/components/myPageMyContentLayout.module.scss
Labels: refactor

#166 refactor: 게시글 컴포넌트 css 수정
  src/components/common/Post/Post.module.scss
  src/components/common/Post/Post.tsx
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.module.scss
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
Labels: refactor

#164 refactor: 로그인, 회원가입 페이지 css수정
  src/components/page-layout/adminLoginLayout/components/adminLoginLayout.module.scss
  src/components/page-layout/loginLayout/components/loginLayout.module.scss
  src/components/page-layout/signUpLayout/components/signUpLayout.module.scss
Labels: refactor

#162 refactor: 게시글 제목 2줄이상 ...으로 처리, 모든 좋아요 기능에 낙관적 업데이트 적용
  src/apis/post/index.ts
  src/components/common/Post/Post.module.scss
  src/components/common/Post/Post.tsx
  src/components/common/Post/PostHeart/PostHeart.tsx
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/GiverPostList/GiverPostList.tsx
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.module.scss
  src/components/page-layout/HomeLayout/components/PostList/TakerPostList/TakerPostList.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeLayout/components/helpMeLayout.module.scss
  src/components/page-layout/helpMeLayout/components/helpMeLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouLayout/components/helpYouLayout.module.scss
  src/components/page-layout/helpYouLayout/components/helpYouLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.module.scss
Labels: refactor

#172 refactor: dropdown, sse, 게시글 상세 페이지 수정
  src/components/common/Chat/Chat.tsx
  src/components/common/DropDown/DropDown.module.scss
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/RadioInput/RadioInput.module.scss
  src/components/common/ReportForm/ReportForm.module.scss
  src/components/common/ReportForm/ReportForm.tsx
  src/components/page-layout/chatLayout/apis/getAllChatList.ts
  src/components/page-layout/chatLayout/components/ChatList/ChatList.tsx
  src/components/page-layout/chatLayout/components/ChatList/ChatListContent/ChatListContent.tsx
  src/components/page-layout/chatLayout/components/ChatList/ChatListHeader/ChatListHeader.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/CertifyVolunteeringModal/CertifyVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/DeclarationModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/DeclarationModal/DeclarationModal.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/RegisterCertifyVolunteeringModal/RegisterCertifyVolunteeringModal.tsx
  src/components/page-layout/chatLayout/components/chatLayout.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.module.scss
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.module.scss
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
  src/components/page-layout/myPageFinishedLayout/components/MyPageCertifyVolunteeringModal/MyPageCertifyVolunteeringModal.tsx
Labels: refactor

#175 feat: 설문 조사 페이지
  public/images/logo.svg
  src/components/common/Header/User/Login/Login.tsx
  src/components/page-layout/surveyLayout/apis/postSurvey.ts
  src/components/page-layout/surveyLayout/components/surveyLayout.module.scss
  src/components/page-layout/surveyLayout/components/surveyLayout.tsx
  src/pages/survey/index.tsx
Labels: feat

#178 refactor: cors, heartbeatTimeout으로 인한 에러 처리
  src/components/common/Comment/Comment.module.scss
  src/components/common/Comment/Comment.tsx
  src/components/common/Header/User/Login/AlarmDropDown/AlarmDropDown.tsx
  src/components/common/Header/User/Login/Login.tsx
  src/components/common/Header/hooks/useNotification.ts
  src/components/common/Header/utils/index.ts
Labels: refactor

#181 refactor 회원가입 페이지
  src/components/page-layout/signUpLayout/components/signUpLayout.module.scss
  src/components/page-layout/signUpLayout/components/signUpLayout.tsx
  src/types/error/index.ts
Labels: refactor

#183 refactor: 로그인 페이지 수정
  src/components/page-layout/adminLoginLayout/components/adminLoginLayout.module.scss
  src/components/page-layout/adminLoginLayout/components/adminLoginLayout.tsx
  src/components/page-layout/loginLayout/components/loginLayout.module.scss
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/components/page-layout/signUpLayout/components/signUpLayout.tsx
Labels: refactor

#185 refactor: 헤더
  public/images/logo.svg
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Header/User/DropDown/DropDown.module.scss
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/Header/User/Login/Login.module.scss
  src/components/common/Header/User/Login/Login.tsx
Labels: refactor

#187 refactor: 게시글 작성 페이지
  src/components/common/MyInfoCard/MyInfoCard.module.scss
  src/components/common/MyInfoCard/MyInfoCard.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.module.scss
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.module.scss
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
Labels: refactor

#190 refactor: 관리자 페이지 수정
  src/components/common/Chat/Chat.module.scss
  src/components/page-layout/chatLayout/components/ChatList/ChatListContent/ChatListContent.module.scss
  src/components/page-layout/chatLayout/components/ChatList/MyInfo/MyInfo.module.scss
  src/components/page-layout/chatLayout/components/ChatList/MyInfo/MyInfo.tsx
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/RegisterCertifyVolunteeringModal/RegisterCertifyVolunteeringModal.module.scss
  src/components/page-layout/chatLayout/components/ChatingRoom/ChatingRoomContent/RegisterCertifyVolunteeringModal/RegisterCertifyVolunteeringModal.tsx
  src/components/page-layout/declarationLayout/components/DeclarationContent/DeclarationContent.tsx
  src/components/page-layout/declarationLayout/components/declarationLayout.tsx
  src/components/page-layout/helpMeRegisterLayout/components/helpMeRegisterLayout.tsx
  src/components/page-layout/helpYouRegisterLayout/components/helpYouRegisterLayout.tsx
  src/components/page-layout/surveyCompleteLayout/components/SurveyCompleteLayout.module.scss
  src/components/page-layout/surveyCompleteLayout/components/SurveyCompleteLayout.tsx
  src/components/page-layout/surveyLayout/components/surveyLayout.module.scss
  src/components/page-layout/surveyLayout/components/surveyLayout.tsx
  src/constants/route.ts
  src/pages/survey/complete/index.tsx
Labels: refactor

#193 refactor: qa 수정사항 반영
  src/components/page-layout/adminLoginLayout/components/adminLoginLayout.tsx
  src/components/page-layout/chatLayout/components/ChatList/MyInfo/MyInfo.module.scss
  src/components/page-layout/loginLayout/components/loginLayout.tsx
  src/components/page-layout/signUpLayout/components/signUpLayout.tsx
  src/components/page-layout/surveyCompleteLayout/components/SurveyCompleteLayout.module.scss
  src/components/page-layout/surveyCompleteLayout/components/SurveyCompleteLayout.tsx
  src/components/page-layout/surveyLayout/components/surveyLayout.tsx
Labels: feat, refactor

#194 refactor: 로그아웃 시 도와줄래요? 도와줄게요! api 호출
  src/components/common/Header/User/DropDown/DropDown.tsx
Labels: refactor

#196 refactor: qa 수정사항 반영
  src/components/common/Comment/ChatButton/ChatButton.module.scss
  src/components/common/Comment/ChatButton/ChatButton.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
Labels: feat

#197 feat: 로그인이 필요한 페이지에서 로그인이 안돼있을 시 로그인 페이지로 리다이렉트
  src/components/page-layout/certificationDetailLayout/components/CertificationDetailLayout.tsx
  src/components/page-layout/certificationLayout/components/certificationLayout.tsx
  src/components/page-layout/chatLayout/components/chatLayout.tsx
  src/components/page-layout/chattingRoomDeclarationDetailLayout/components/chattingRoomDeclarationDetailLayout.tsx
  src/components/page-layout/commentDeclarationDetailLayout/components/commentDeclarationDetailLayout.tsx
  src/components/page-layout/declarationLayout/components/declarationLayout.tsx
  src/components/page-layout/postDeclarationDetailLayout/components/postDeclarationDetailLayout.tsx
  src/components/page-layout/userAdminLayout/components/userAdminLayout.tsx
Labels: feat

#198 refactor: 입력받는 부분 현재 글자 수 보여주게 수정
  src/components/common/Header/User/DropDown/DropDown.tsx
  src/components/common/LikesPost/LikesPost.tsx
  src/components/page-layout/MyPageHelpYouLayout/components/myPageHelpYouLayout.module.scss
  src/components/page-layout/MyPageHelpYouLayout/components/myPageHelpYouLayout.tsx
  src/components/page-layout/certificationLayout/components/certificationLayout.tsx
  src/components/page-layout/declarationLayout/components/declarationLayout.tsx
  src/components/page-layout/helpMeDetailLayout/components/helpMeDetailLayout.tsx
  src/components/page-layout/helpMeEditLayout/apis/putHelpMeRegister.ts
  src/components/page-layout/helpMeEditLayout/components/helpMeEditLayout.module.scss
  src/components/page-layout/helpMeEditLayout/components/helpMeEditLayout.tsx
  src/components/page-layout/helpYouDetailLayout/components/helpYouDetailLayout.tsx
  src/components/page-layout/helpYouEditLayout/components/helpYouEditLayout.module.scss
  src/components/page-layout/helpYouEditLayout/components/helpYouEditLayout.tsx
  src/components/page-layout/myPageEditLayout/components/MyInfoEditFrom/MyInfoEditForm.tsx
  src/components/page-layout/myPageFinishedLayout/components/FinishedPost/FinishedPost.tsx
  src/components/page-layout/myPageFinishedLayout/components/MyPageCertifyVolunteeringModal/MyPageCertifyVolunteeringModal.tsx
  src/components/page-layout/myPageHelpMeLayout/apis/getMyComment.ts
  src/components/page-layout/myPageHelpMeLayout/apis/getMyPost.ts
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.module.scss
  src/components/page-layout/myPageHelpMeLayout/components/MyRegisterPost/MyRegisterPost.tsx
  src/components/page-layout/myPageHelpMeLayout/components/myPageHelpMeLayout.module.scss
  src/components/page-layout/myPageHelpMeLayout/components/myPageHelpMeLayout.tsx
  src/components/page-layout/myPageLayout/components/MyInfo/MyInfo.module.scss
  src/components/page-layout/myPageMyContentLayout/components/MyRegisterPost/myRegisterPost.tsx
  src/components/page-layout/userAdminLayout/components/userAdminLayout.tsx
  src/pages/my-page/help-me/index.tsx
  src/pages/my-page/help-you/index.tsx
Labels: refactor

#199 refactor: 회원 가입 유효성 검사
  src/components/page-layout/signUpLayout/components/signUpLayout.tsx
Labels: refactor
